# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://fabricmc.net/develop/
minecraft_version=26.1.2
loader_version=0.19.2
fabric_version=0.146.1+26.1.2

# Mod Properties
mod_version=1.15+mc26.1.2
maven_group=me.juancarloscp52
archives_base_name=Entropy

# Dependencies
modmenu_version=18.0.0-alpha.8
pircbotx_version=2.3.1
slf4j_version=1.7.36
jda_version=5.6.1